# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - gem install compass
  - npm install --global grunt-cli bower cordova
  - npm install
  - bower install

build: off

test_script:
  - grunt build
  - cordova platform add wp8
  - cordova build wp8